NAME=KnightOS
VERSION=0.1-alpha
COLOR_OUTPUT=true
THEME=flatly
KNIGHT_LANG=en
USE_SUDO=true
AUTO_UPDATE=false
LOG_LEVEL=info
LOG_DIR=core/logs
GPU=nvidia
CPU=intel
ENABLE_GAMEMODE=true
ENABLE_ZRAM=false
ENABLE_TRACKER=false
ENABLE_BLUETOOTH=false
BOOT_THEME=Knight
GTK_THEME=Knight
